### ISSUE TITLE
Application freezes when opening a document

### ISSUE THREAD

**Issue by wohltat** [ceremcem/build-freecad-asm3#26]
I compiled FreeCAD according to the instructions using the container approach from the freshly cloned repo. It seemed to be be successful but if i try to open an existing or a new document the application freezes with following error in the terminal:

``` 
> ./freecad.sh --verbose                                                                                                            
[sudo] password for username: 
FreeCAD 0.20, Libs: 0.20R31657 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2021
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
During initialization the error "No module named 'pivy'" occurred in freecad.asm3
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 158, in InitApplications
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fc/fc-build/Release/Mod/asm3/freecad/asm3/init_gui.py", line 3, in <module>
    from . import gui
  File "/home/fc/fc-build/Release/Mod/asm3/freecad/asm3/gui.py", line 4, in <module>
    from pivy import coin
ModuleNotFoundError: No module named 'pivy'
--------------------------------------------------------------------------------
connect failed: No such file or directory

```
[build-freecad-asm3-error.log](https://github.com/ceremcem/build-freecad-asm3/files/11169368/build-freecad-asm3-error.log)

**Comment by wohltat** [comment]
I used maybe an old container. I repeated everything and now there is a different error but the same freeze:

```
>>> ./freecad.sh --verbose                                                                                                             ‹git:master ✔› 16:27.59 Thu Apr 06 2023 >>> 
[sudo] password for boogieman: 
FreeCAD 0.20, Libs: 0.20R31657 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2021
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
connect failed: No such file or directory

```
[build-freecad-asm3-error2.log](https://github.com/ceremcem/build-freecad-asm3/files/11173024/build-freecad-asm3-error2.log)

**Comment by ceremcem** [comment]
Maybe something changed with the FreeCAD code. I'm on it ASAP.
